name = "tawaw18agent"
main = "src/worker.ts"
compatibility_date = "2026-03-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[assets]]
directory = "./dist"
binding = "ASSETS"
